### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dotellie** [Deep-Learning-Cloud/goto-church#3]
- [x] Make results screen look nicer (Ellie)
- [x] Generate from text input
- [x] Regeneration (Ellie)
- [x] Donate (Arvid)
- [x] Loading feedback (Ellie)
- [x] Better prompts (Arvid)
- [x] Artificial delay (Ellie)
- [x] Show previously generated quotes (Ellie)
- [x] Comparison of framworks & README

## Less priority

- [ ] Refactor to [actions](https://qwik.dev/docs/action)
- [x] Header
- [ ] Proper database (probably with D1 and Drizzle)
